# Generated by Django 6.0.1 on 2026-09-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_breathingentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='sentiment',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
